sudo: required
language: cpp
compiler:
  - gcc
before_install:
- sudo apt-get -qq update && sudo apt-get install -y texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended latexmk
- mkdir -p ~/.fonts/
- #cp -rf fonts/* ~/.fonts/
- sudo fc-cache -f -v
script:
- latexmk -pdf -e '$pdflatex=q/xelatex %O %S/' report/report.tex -f
deploy:
  provider: releases
  api_key:
    secure: j/LhHx3e85LoSIC3nXGJEYyetomvlVYoHi5KRxsESTj6YiHO1J$
  file: report/report.pdf
  skip_cleanup: true
  on:
    repo: jamesmstone/Knowledge-Technologies-Project-1

